# Generated by Django 5.1.7 on 2026-02-05 16:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('telefono', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('grado_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('carrera', models.CharField(blank=True, max_length=150, null=True)),
                ('trabajo', models.CharField(blank=True, max_length=150, null=True)),
                ('referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Perú', max_length=100)),
                ('uso_imagen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(choices=[('VDF', 'VARIADORES DE FRECUENCIA'), ('REDES', 'REDES INDUSTRIALES'), ('PLC1', 'PLC NIVEL 1'), ('PLC2', 'PLC NIVEL 2'), ('INST', 'INSTRUMENTACION INDUSTRIAL'), ('ELEC_LOGO', 'AUTOMATIZACION PARA EL ARRANQUE DE MOTORES ELECTRICOS CON PLC LOGO V8!'), ('LOGO', 'AUTOMATIZACION INDUSTRIAL CON PLC LOGO V8!')], max_length=255)),
                ('fecha', models.DateField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('horario', models.TimeField()),
                ('duracion', models.IntegerField(help_text='Duración en horas')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20)),
                ('tipo_horario', models.CharField(choices=[('full', 'Full Day (3 semanas)'), ('extendida', 'Extendida (6 semanas)'), ('personalizado', 'Personalizado')], max_length=20)),
                ('dias', models.JSONField(blank=True, default=list)),
                ('costo_curso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('primer_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('porcentaje', models.PositiveIntegerField()),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fechas_personalizadas', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('truncado', 'Truncado')], default='activa', max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_trunco', models.CharField(blank=True, choices=[('horarios', 'Horarios'), ('economico', 'Económico'), ('salud', 'Salud'), ('viaje', 'Viaje / Mudanza'), ('insatisfaccion', 'Insatisfacción'), ('otro', 'Otro')], max_length=30, null=True)),
                ('razon_trunco', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_entregado', models.BooleanField(default=False)),
                ('manual_entregado_en', models.DateTimeField(blank=True, null=True)),
                ('video_enviado', models.BooleanField(default=False)),
                ('video_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='cursos.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egresado', to='cursos.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_vencimiento', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='cursos.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('horario', models.TimeField(default='08:00:00')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('matriculas', models.ManyToManyField(blank=True, to='cursos.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='cursos.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(default=0)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('plin', 'Plin'), ('yape', 'Yape'), ('izipay', 'Izipay'), ('interbank', 'Interbank'), ('culqi', 'Culqi'), ('efectivo', 'Efectivo')], max_length=30, null=True)),
                ('concepto', models.CharField(choices=[('anticipo', 'Anticipo'), ('cuota_1', 'Cuota 1'), ('cuota_2', 'Cuota 2'), ('reprogramacion', 'Reprogramación')], max_length=50)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_extra', to='cursos.alumno')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cursos.cuota')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cursos.matricula')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reprogramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateField()),
                ('fecha_nueva', models.DateField()),
                ('solicitante', models.CharField(choices=[('WEEIN', 'Weein'), ('ALUMNO', 'Alumno')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pagado', models.BooleanField(default=False)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones_hist', to='cursos.clase')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones_hist', to='cursos.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='cursos.categoriaservicio')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado', models.PositiveIntegerField(help_text='Tiempo en minutos para completar la tarea')),
                ('vencida', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
                ('area_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='cursos.area')),
                ('tarea_compartida', models.ManyToManyField(blank=True, related_name='tareas_compartidas', to='cursos.area')),
                ('tarea_delegada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre_tema', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='cursos.curso')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('curso', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='VentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('metodo_pago', models.CharField(blank=True, choices=[('plin', 'Plin'), ('yape', 'Yape'), ('izipay', 'Izipay'), ('interbank', 'Interbank'), ('culqi', 'Culqi'), ('efectivo', 'Efectivo')], max_length=30, null=True)),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_servicios', to='cursos.alumno')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_servicios', to='cursos.matricula')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='cursos.servicioextra')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.clase')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.matricula')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.unidadcurso')),
            ],
            options={
                'unique_together': {('matricula', 'unidad', 'fecha')},
            },
        ),
    ]
