# Generated by Django 5.1.7 on 2025-03-21 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='fecha',
        ),
        migrations.AddField(
            model_name='clase',
            name='matriculas',
            field=models.ManyToManyField(blank=True, to='cursos.matricula'),
        ),
        migrations.AddField(
            model_name='diaestudio',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='diaestudio',
            name='dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='dias_estudio',
        ),
        migrations.AddField(
            model_name='matricula',
            name='dias_estudio',
            field=models.ManyToManyField(to='cursos.diaestudio'),
        ),
    ]
