# Generated by Django 5.1.7 on 2026-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_horario',
            field=models.CharField(choices=[('full', 'Full Day (3 semanas)'), ('extendida', 'Extendida (6 semanas)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('plin', 'Plin'), ('yape', 'Yape'), ('izipay', 'Izipay'), ('interbank', 'Interbank'), ('culqi', 'Culqi'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal'), ('bbva', 'BBVA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('plin', 'Plin'), ('yape', 'Yape'), ('izipay', 'Izipay'), ('interbank', 'Interbank'), ('culqi', 'Culqi'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal'), ('bbva', 'BBVA')], max_length=30, null=True),
        ),
    ]
