# Generated by Django 5.1.7 on 2026-02-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_alumno_dni_alter_matricula_tipo_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaunidad',
            name='horario',
            field=models.CharField(blank=True, choices=[('9-1', '9-1'), ('2-6', '2-6'), ('9-6', '9-6'), ('7-9', '7-9')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Documento de identidad'),
        ),
    ]
