# Generated by Django 5.1.7 on 2025-03-22 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_clase_fecha_clase_matriculas_diaestudio_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
