# Generated by Django 5.1.7 on 2026-03-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_asistenciaunidad_horario_alter_alumno_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('standby', 'Standby'), ('realizada', 'Realizada')], default='programada', max_length=15),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
