# Generated by Django 5.1.7 on 2025-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='dias_estudio',
            field=models.ManyToManyField(blank=True, to='cursos.diaestudio'),
        ),
    ]
