# Generated by Django 5.1.7 on 2026-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_clase_estado_alter_clase_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
