# Generated by Django 5.1.7 on 2025-03-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_matricula_dias_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaestudio',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
    ]
