# Generated by Django 5.1.7 on 2025-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='dias',
            field=models.JSONField(default=list),
        ),
    ]
