# Generated by Django 5.1.7 on 2025-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_matricula_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='fechas',
            field=models.JSONField(default=list),
        ),
    ]
