# Generated by Django 5.1.7 on 2025-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_curso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(choices=[('PLC NIVEL 1', 'PLC NIVEL 1'), ('PLC NIVEL 2', 'PLC NIVEL 2'), ('INSTRUMENTACION INDUSTRIAL', 'INSTRUMENTACION INDUSTRIAL'), ('VARIADORES DE FRECUENCIA', 'VARIADORES DE FRECUENCIA'), ('PLC LOGO! V8', 'PLC LOGO! V8'), ('REDES INDUSTRIALES', 'REDES INDUSTRIALES')], max_length=255),
        ),
    ]
