# Generated by Django 5.1.7 on 2025-04-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_tarea_delegado_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='delegado_a',
        ),
    ]
