# Generated by Django 5.1.7 on 2025-05-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_remove_tarea_delegado_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='vencida',
            field=models.BooleanField(default=False),
        ),
    ]
