# Generated by Django 5.1.7 on 2025-05-07 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_tarea_vencida'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre_tema', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='cursos.curso')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('curso', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.matricula')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.unidadcurso')),
            ],
            options={
                'unique_together': {('matricula', 'unidad')},
            },
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
