# Generated by Django 5.1.7 on 2025-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_unidadcurso_asistenciaunidad_delete_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='vencida',
        ),
        migrations.AddField(
            model_name='tarea',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
