# Generated by Django 5.1.7 on 2025-05-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_remove_tarea_vencida_tarea_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='vencida',
            field=models.BooleanField(default=False),
        ),
    ]
