# Generated by Django 5.1.7 on 2026-01-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_alumno_carrera_alumno_departamento_alumno_distrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='dias_estudio',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='fechas',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='numero_semanas',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='turno',
        ),
        migrations.AddField(
            model_name='matricula',
            name='costo_curso',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='fechas_personalizadas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matricula',
            name='porcentaje',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='primer_pago',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='tipo_horario',
            field=models.CharField(choices=[('full', 'Full Day (3 semanas)'), ('extendida', 'Extendida (6 semanas)'), ('personalizado', 'Personalizado')], default='noche', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='dias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20),
        ),
    ]
