# Generated by Django 5.1.7 on 2026-01-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_remove_matricula_dias_estudio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('concepto', models.CharField(choices=[('anticipo', 'Anticipo'), ('cuota_1', 'Cuota 1'), ('cuota_2', 'Cuota 2')], max_length=50)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cursos.matricula')),
            ],
        ),
    ]
