# Generated by Django 5.1.7 on 2026-01-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0024_pago_activo_pago_registrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
            preserve_default=False,
        ),
    ]
