# Generated by Django 5.1.7 on 2026-01-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0025_matricula_precio_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
