# Generated by Django 5.1.7 on 2026-01-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0026_cuota_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaunidad',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
