# Generated by Django 5.1.7 on 2026-01-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0028_egresado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadcurso',
            options={},
        ),
        migrations.AddField(
            model_name='unidadcurso',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
