# Generated by Django 5.1.7 on 2026-01-19 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0029_alter_unidadcurso_options_unidadcurso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
