# Generated by Django 5.1.7 on 2026-01-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0030_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('plin', 'Plin'), ('yape', 'Yape'), ('izipay', 'Izipay'), ('interbank', 'Interbank'), ('culqi', 'Culqi'), ('efectivo', 'Efectivo')], default='efectivo', max_length=20, null=True),
        ),
    ]
