# Generated by Django 5.1.7 on 2026-01-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0031_remove_pago_fecha_pago_pago_fecha_pago_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cursos.cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('plin', 'Plin'), ('yape', 'Yape'), ('izipay', 'Izipay'), ('interbank', 'Interbank'), ('culqi', 'Culqi'), ('efectivo', 'Efectivo')], max_length=30, null=True),
        ),
    ]
