# Generated by Django 5.1.7 on 2026-01-20 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0032_pago_cuota_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadcurso',
            options={'ordering': ['numero']},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaunidad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistenciaunidad',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.clase'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaunidad',
            unique_together={('matricula', 'unidad', 'clase')},
        ),
    ]
