# Generated by Django 5.1.7 on 2026-01-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0033_alter_unidadcurso_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaunidad',
            unique_together={('matricula', 'unidad', 'fecha')},
        ),
    ]
