# Generated by Django 5.1.7 on 2026-01-22 00:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0034_alter_asistenciaunidad_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='cursos.matricula')),
            ],
        ),
    ]
