# Generated by Django 5.1.7 on 2026-01-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0035_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
